apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.appReplicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: "{{ .Values.appImage }}:{{ .Values.appVersion }}"
        ports:
        - containerPort: {{ .Values.containerPort }}
        env:
        {{- range .Values.containersEnvVars }}
        - name: {{ .name }}
          value: "{{ .value }}"
        {{- end }}

        {{- if .Values.healthCheck.enabled }}
        readinessProbe:
          periodSeconds: {{ .Values.healthCheck.readiness.periodSeconds }}
          initialDelaySeconds: {{ .Values.healthCheck.readiness.initialDelaySeconds }}
          {{- if eq .Values.healthCheck.type "grpc" }}
          grpc:
            port: {{ .Values.healthCheck.port | default .Values.containerPort }}
          {{- else if eq .Values.healthCheck.type "http" }}
          httpGet:
            path: {{ .Values.healthCheck.path }}
            port: {{ .Values.healthCheck.port }}
            {{- if .Values.healthCheck.httpHeaders }}
            httpHeaders:
            {{- range .Values.healthCheck.httpHeaders }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}
            {{- end }}
          {{- end }}
        livenessProbe:
          periodSeconds: {{ .Values.healthCheck.liveness.periodSeconds }}
          initialDelaySeconds: {{ .Values.healthCheck.liveness.initialDelaySeconds }}
          {{- if eq .Values.healthCheck.type "grpc" }}
          grpc:
            port: {{ .Values.healthCheck.port | default .Values.containerPort }}
          {{- else if eq .Values.healthCheck.type "http" }}
          httpGet:
            path: {{ .Values.healthCheck.path }}
            port: {{ .Values.healthCheck.port }}
            {{- if .Values.healthCheck.httpHeaders }}
            httpHeaders:
            {{- range .Values.healthCheck.httpHeaders }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}
            {{- end }}
          {{- end }}
        {{- end }}
        resources:
          requests:
            cpu: {{ .Values.requestsCpu}}
            memory: {{ .Values.requestsMemory}}
          limits:
            cpu: {{ .Values.limitsCpu}}
            memory: {{ .Values.limitsMemory}}